version: "3"

services:
  postgres:
    image: "postgres:10"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/